# Generated by Django 4.2.23 on 2025-06-19 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Chambre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("maison_id", models.IntegerField()),
                ("proprietaire_id", models.IntegerField()),
                ("titre", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("taille", models.CharField(max_length=20)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("simple", "Simple"),
                            ("appartement", "Appartement"),
                            ("maison", "Maison"),
                        ],
                        max_length=20,
                    ),
                ),
                ("meublee", models.BooleanField()),
                ("salle_de_bain", models.BooleanField()),
                ("prix", models.DecimalField(decimal_places=2, max_digits=10)),
                ("disponible", models.BooleanField(default=True)),
                ("cree_le", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
